apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: secret
  JWT_HTTP_ONLY: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  JWT_HTTP_ONLY: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: youcancallmegus/auth:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP